version: '3'

services:
  djangoapp:
    build: .
    image: bonita/ai_server_proto
    container_name: ai_server_proto_1
    volumes:
      - .:/opt/services/djangoapp/src
      - ./djangoapp-entrypoint.sh:/opt/services/djangoapp/src/djangoapp-entrypoint.sh
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/services/djangoapp/src/My First Project-cf397e8f9d9b.json
    networks:
      - nginx_network
      - database1_network
    command:
      - /opt/services/djangoapp/src/djangoapp-entrypoint.sh
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    container_name: nginx_server_1
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:10
    container_name: ai_server_proto_db_1
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data


networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
