version: '3'

services:
  djangoapp:
    build: .
    image: bonita/ai_server_proto
    container_name: ai_server_proto_1
    volumes:
      - .:/opt/services/djangoapp/src
      - ./djangoapp-entrypoint.sh:/opt/services/djangoapp/src/djangoapp-entrypoint.sh
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/services/djangoapp/src/My First Project-cf397e8f9d9b.json
    networks:
      - nginx_network
    command:
      - /opt/services/djangoapp/src/djangoapp-entrypoint.sh

  nginx:
    image: nginx:1.13
    container_name: nginx_server_1
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
